version: '2'
volumes:
  dbdata:
    external:
      name: 'cddevel-dbdata'
  public:
  uploads:
    external:
      name: 'cddevel-uploads'
  queuedata:
    external:
      name: 'cddevel-queuedata'

networks:
  www_default:
    external:
      name: www_default
  cddevel:

services:
  db:
    image: 'postgres:9.5'
    env_file: .rbenv-vars
    networks:
     - cddevel
    volumes:
      - 'dbdata:/var/lib/postgresql/data'

  smtp:
    image: 'dtheus/postfix:jessie'
    networks:
     - cddevel
    ports:
      - '25'
    env_file: .rbenv-vars
    volumes: 
      - '/etc/opendkim/keys/cddevel.com:/etc/opendkim/keys/cddevel.com'
    environment:
      VIRTUAL_HOST: mail.cddevel.com
      VIRTUAL_PORT: 25

  app: &app
    build: .
    networks:
      - cddevel
      - www_default
    depends_on:
      - db
      - smtp
      - sidekiq
    env_file: .rbenv-vars
    volumes:
      - 'public:/app/public'
      - 'uploads:/app/public/uploads'
    environment:
      VIRTUAL_HOST: cddevel.com
      VIRTUAL_PORT: 3000

  sidekiq:
    <<: *app
    command: bundle exec sidekiq
    depends_on:
      - db
      - queue
    environment: {}

  static:
    image: nginx
    volumes:
      -  public:/usr/share/nginx/html
      -  uploads:/usr/share/nginx/html/uploads
    depends_on:
      - app
    networks:
      - cddevel
      - www_default
    environment:
      VIRTUAL_HOST: assets.cddevel.com
      VIRTUAL_PORT: 80

  queue:
    image: redis:3.0
    env_file: .rbenv-vars
    networks:
     - cddevel
    volumes:
      - 'queuedata:/var/redis'
    command: redis-server --appendonly yes

  cache:
    image: redis:3.0
    networks:
      - cddevel
    env_file: .rbenv-vars

