version: '2'
volumes:
  dbdata:
    external:
      name: 'cddevel-dbdata'
  public:
  uploads:
    external:
      name: 'cddevel-uploads'
  queuedata:
    external:
      name: 'cddevel-queuedata'

services:
  db:
    image: 'postgres:9.5'
    env_file: .rbenv-vars
    volumes:
      - 'dbdata:/var/lib/pgsql'

  smtp:
    image: 'dtheus/postfix:jessie'
    ports:
      - '25:25'
    env_file: .rbenv-vars
    volumes: 
      - '/etc/opendkim/keys/cddevel.com:/etc/opendkim/keys/cddevel.com'

  app: &app
    build: .
    depends_on:
      - db
      - smtp
      - sidekiq
    env_file: .rbenv-vars
    volumes:
      - 'public:/var/www/cddevel.com/public'
      - 'uploads:/var/www/cddevel.com/uploads'
    environment:
      VIRTUAL_HOST: cddevel.com
      VIRTUAL_PORT: 3000

  sidekiq:
    <<: *app
    command: bundle exec sidekiq
    depends_on:
      - db
      - queue

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/nginx/vhost.d/default:/etc/nginx/vhost.d/default
      - public:/app/public
      - uploads:/app/public/uploads
    depends_on:
      - app

  queue:
    image: redis:3.0
    env_file: .rbenv-vars
    volumes:
      - 'queuedata:/var/redis'
    command: redis-server --appendonly yes

  cache:
    image: redis:3.0
    env_file: .rbenv-vars

