version: '2'
volumes:
  dbdata:
    external:
      name: 'cddevel-dbdata'
  uploads:
    external:
      name: 'cddevel-uploads'
  queuedata:
    external:
      name: 'cddevel-queuedata'

services:
  db:
    image: 'dtheus/postgres'
    env_file: .rbenv-vars
    volumes:
      - 'dbdata:/var/lib/pgsql'

  smtp:
    image: 'dtheus/postfix-dkim'
    ports:
      - '25:25'
    env_file: .rbenv-vars
    volumes: 
      - '/etc/opendkim/keys/cddevel.com:/etc/opendkim/keys/cddevel.com'

  app: &app
    build: .
    depends_on:
      - db
      - smtp
      - sidekiq
    env_file: .rbenv-vars
    volumes:
      - '/home/web/app/public'
      - 'uploads:/home/web/app/public/uploads'
    environment:
      VIRTUAL_HOST: cddevel.com

  sidekiq:
    <<: *app
    command: bundle exec sidekiq
    depends_on:
      - db
      - queue

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/nginx/vhost.d/default:/etc/nginx/vhost.d/default
    volumes_from:
      - app:ro
    depends_on:
      - app

  queue:
    build:
      context: 'https://github.com/d-theus/redis-persistence-dockerfile.git'
    env_file: .rbenv-vars
    volumes:
      - 'queuedata:/var/redis'

  cache:
    build:
      context: 'https://github.com/d-theus/redis-cache-dockerfile.git'
    env_file: .rbenv-vars

