source 'https://rubygems.org'

gem 'rails', '4.1.7'

gem 'carrierwave'
gem 'carrierwave_backgrounder'
gem 'coffee-rails', '~> 4.0.0'
gem 'devise'
gem 'devise-i18n-bootstrap'
gem 'haml-rails'
gem 'jquery-rails'
gem 'less-rails'
gem 'mini_magick'
gem 'pg'
gem 'pry-rails'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'simple_form'
gem 'sitemap_generator'
gem 'spring',        group: :development
gem 'therubyracer'
gem 'thin'
gem 'turbolinks'
gem 'twitter-bootstrap-rails'
gem 'uglifier', '>= 1.3.0'
gem 'active_model_serializers'
gem 'will_paginate-bootstrap'
gem 'item'
gem 'acts-as-taggable-on', '~> 4.0'
gem 'friendly_id', '~> 5.1.0'
gem 'redcarpet'
gem 'rouge'
gem 'redis-rails'
gem 'sidekiq'
gem 'rails-observers'

group :development do
  gem 'capistrano'
  gem 'capistrano-rbenv'
  gem 'capistrano-rails'
  gem 'chef'
  gem 'knife-solo'
  gem 'knife-solo_data_bag'
  gem 'bullet'
  gem 'rack-mini-profiler'
  gem 'letter_opener'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'rspec-html-matchers'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'factory_girl_rails'
  gem 'timecop'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'database_cleaner'
end
